version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      # Anonymous volume:
      - /app/node_modules