version: '3'
services:
  backstage-app-mandragora:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    container_name: container_backstage_app_mandragora
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      # Anonymous volume:
      - /app/node_modules